---
- name: create omnibus-mttrapd-secgroup
  become: no
  local_action:
    module:      ec2_group
    name:        omnibus
    purge_rules: false
    purge_rules_egress: false
    description: secgroup for omnibus access
    vpc_id:      "{{vpc_id}}"
    region:      "{{ec2_region}}"
    state:       present
    rules:
     - proto:     tcp
       from_port: 4100
       to_port:   4100
       cidr_ip:
         - 172.0.0.0/8
         - "{{networks['euw01.nms.viasat.io']}}"
         - "{{networks['aps01.nms.viasat.io']}}"
         - "{{networks['nms.viasat.io']}}"
     - proto:     tcp
       from_port: 8080
       to_port:   8080
       cidr_ip:
         - 172.0.0.0/8
         - 10.43.16.0/24
         - 10.137.18.0/24
         - 10.137.30.0/24
         - "{{networks['euw01.nms.viasat.io']}}"
         - "{{networks['aps01.nms.viasat.io']}}"
         - "{{networks['nms.viasat.io']}}"
     - proto:     tcp
       from_port: 4301
       to_port:   4301
       cidr_ip:
         - 172.0.0.0/8
         - "{{networks['euw01.nms.viasat.io']}}"
         - "{{networks['aps01.nms.viasat.io']}}"
         - "{{networks['nms.viasat.io']}}"
     - proto:     tcp
       from_port: 4302
       to_port:   4302
       cidr_ip:
         - 172.0.0.0/8
         - "{{networks['euw01.nms.viasat.io']}}"
         - "{{networks['aps01.nms.viasat.io']}}"
         - "{{networks['nms.viasat.io']}}"
     - proto:      tcp
       from_port:  16310
       to_port:    16323
       cidr_ip:
         - "{{networks['euw01.nms.viasat.io']}}"
         - "{{networks['aps01.nms.viasat.io']}}"
         - "{{networks['nms.viasat.io']}}"
         - 172.0.0.0/8
     - proto:     tcp
       from_port: 514
       to_port:   514
       cidr_ip:
         - "{{networks['euw01.nms.viasat.io']}}"
         - "{{networks['aps01.nms.viasat.io']}}"
         - "{{networks['nms.viasat.io']}}"
         - 172.0.0.0/8
     - proto:     udp
       from_port: 514
       to_port:   514
       cidr_ip:
         - 172.0.0.0/8
         - "{{networks['nms.viasat.io']}}"
         - "{{networks['euw01.nms.viasat.io']}}"
         - "{{networks['aps01.nms.viasat.io']}}"
     - proto:     udp
       from_port: 161 
       to_port:   162 
       cidr_ip:
         - 172.0.0.0/8
         - 10.0.0.0/8
     - proto:     tcp
       from_port: 161
       to_port:   162
       cidr_ip:
         - 172.0.0.0/8
         - 10.0.0.0/8
    rules_egress:
     - proto:     all 
       from_port: 0 
       to_port:   65535 
       cidr_ip:
         - 172.0.0.0/8
         - 10.0.0.0/8


