---
- name: Get WebGUI version
  shell: "/root/IBM/InstallationManager/eclipse/tools/imcl listInstalledPackages -features -long > InstallManager_installed_software.txt; cat InstallManager_installed_software.txt|cut -d\" \" -f5-|cut -d\":\" -f1,2|sed \"s/ :/:/g\"|tail -1|cut -d\" \" -f6"
  become: true
  register: webgui_version

- meta: end_play
  when: webgui_version.stdout == "8.1.0.9" 

- name: Check to see if fixpack is already applied and skip all tasks if it is 
  fail: msg="Fixpack 9 is already applied so this playbook will be skipped"
  when: webgui_version.stdout == "8.1.0.9"

- stat:
    path: /opt/viasat
  register: dircheck

- debug:
    msg: "Path exists and is a directory"
  when: dircheck.stat.isdir is defined and p.stat.isdir

- debug:
    msg: "/opt/viasat isn't defined (path doesn't exist)"
  when: dircheck.stat.isdir is not defined

- name: Use hostnamectl to set static hostname
  shell: "hostnamectl set-hostname {{mywebguiserver}} --static"
  become: true

- name: Get hostname from this device
  shell: "hostname -f"
  args:
    executable: /bin/bash
  register: myhost

- name: Debug myhost
  debug: var=myhost.stdout
#==============================================
# Check to see if webgui is already installed
#==============================================
- name: Check to see if WebGUI process is up 
  shell: "hostnamectl set-hostname {{mywebguiserver}} --static"
  become: true


- stat:
    path: /opt/IBM
  register: dircheck

- debug:
    msg: "Path exists and is a directory"
  when: dircheck.stat.isdir is defined and p.stat.isdir

- debug:
    msg: "/opt/viasat isn't defined (path doesn't exist)"
  when: dircheck.stat.isdir is not defined


#================================================
- name: Get webgui host IP
  shell: "nslookup {{mywebguiserver}}|grep \"Address: 10\"|cut -d \" \" -f2"
  args:
    executable: /bin/bash
  register: mywebguiserverip

- name: Set variable for webgui servers IP Address
  debug: var=mywebguiserverip.stdout

- name: copy webgui config file
  copy:
    src: fixpack-response.xml
    dest: "/opt/viasat/omnibus/configs/webgui/fixpack-response.xml"
    owner: root
    group: root
    mode: 0755
    force: yes

- name: Stop the WebGUI server before applying the fixpack
  shell: "/opt/IBM/JazzSM/profile/bin/startServer.sh server1 -username smadmin -password smadmin &> catchstop1; sleep 10; tail -2 catchstop1|head -1|cut -d\":\" -f1" 
  become: true
  register: catchstop

- name: Set variable for webgui shutdown 
  debug: var=catchstop.stdout

- debug:
    msg: "Validated that the WebGUI server has stopped."
  when: catchstop.stdout == "ADMU4000I" 

- name: Get IBM webgui fixpack 9 IM UpdatePack 
  uri:
    url: https://artifactory.viasat.com/artifactory/maas-generic-local/OMNIbus-v8.1.0-WebGUI-FP9-IM-linux64-UpdatePack.zip 
    method: GET 
    dest: /opt/IBM/tmp/install/fp9/webgui/update/OMNIbus-v8.1.0-WebGUI-FP9-IM-linux64-UpdatePack.zip 
    user: nms_exede_ci-cd 
    password: AKCp2UNConPgDX6sZnkAoRQ1N8Qevm71RrHsTg86kEuC2BaYyeZfrhuRJX6StuSjUgaPNk5Hf 
    force_basic_auth: yes
    status_code: 200,304
    creates: /opt/IBM/tmp/install/fp9/webgui/update/OMNIbus-v8.1.0-WebGUI-FP9-IM-linux64-UpdatePack.zip 
    timeout: 300 

- unarchive:
    src: /opt/IBM/tmp/install/fp9/webgui/update/OMNIbus-v8.1.0-WebGUI-FP9-IM-linux64-UpdatePack.zip 
    dest: /opt/IBM/tmp/install/fp9/webgui/update/
    remote_src: True

- name: Delete the zip file 
  shell: "rm -f /opt/IBM/tmp/install/fp9/webgui/update/OMNIbus-v8.1.0-WebGUI-FP9-IM-linux64-UpdatePack.zip"
  become: true

- name: Get IBM webgui fixpack 9 IM UpdatePack
  uri:
    url: https://artifactory.viasat.com/artifactory/maas-generic-local/OMNIbus-v8.1.0-WebGUI-FP9-IM-Extensions-linux64-UpdatePack.zip
    method: GET
    dest: /opt/IBM/tmp/install/fp9/webgui/ext/OMNIbus-v8.1.0-WebGUI-FP9-IM-Extensions-linux64-UpdatePack.zip
    user: nms_exede_ci-cd
    password: AKCp2UNConPgDX6sZnkAoRQ1N8Qevm71RrHsTg86kEuC2BaYyeZfrhuRJX6StuSjUgaPNk5Hf
    force_basic_auth: yes
    status_code: 200,304
    creates: /opt/IBM/tmp/install/fp9/webgui/ext/OMNIbus-v8.1.0-WebGUI-FP9-IM-Extensions-linux64-UpdatePack.zip
    timeout: 300

- unarchive:
    src: /opt/IBM/tmp/install/fp9/webgui/ext/OMNIbus-v8.1.0-WebGUI-FP9-IM-linux64-UpdatePack.zip
    dest: /opt/IBM/tmp/install/fp9/webgui/ext/
    remote_src: True

- name: Delete the zip file
  shell: "rm -f /opt/IBM/tmp/install/fp9/webgui/ext/OMNIbus-v8.1.0-WebGUI-FP9-IM-linux64-UpdatePack.zip" 
  become: true

- name: Get IBM JAZZ Install file
  uri:
    url: https://artifactory.viasat.com/artifactory/maas-generic-local/JAZZ_FOR_SM_1.1.3.0_FOR_LNX.zip
    method: GET
    dest: /opt/IBM/tmp/install/fp9/jazz/JAZZ_FOR_SM_1.1.3.0_FOR_LNX.zip
    user: nms_exede_ci-cd
    password: AKCp2UNConPgDX6sZnkAoRQ1N8Qevm71RrHsTg86kEuC2BaYyeZfrhuRJX6StuSjUgaPNk5Hf
    force_basic_auth: yes
    status_code: 200,304
    creates: /opt/IBM/tmp/install/fp9/jazz/JAZZ_FOR_SM_1.1.3.0_FOR_LNX.zip
    timeout: 300

- unarchive:
    src: /opt/IBM/tmp/install/fp9/jazz/JAZZ_FOR_SM_1.1.3.0_FOR_LNX.zip
    dest: /opt/IBM/tmp/install/fp9/jazz/
    remote_src: True

- name: Delete the zip file
  shell: "rm -f /opt/IBM/tmp/install/fp9/jazz/JAZZ_FOR_SM_1.1.3.0_FOR_LNX.zip" 
  become: true

- name: Get IBM WAS Install file
  uri:
    url: https://artifactory.viasat.com/artifactory/maas-generic-local/WAS_V8.5.5.9_FOR_JSM_FOR_LINUX_ML.zip
    method: GET
    dest: /opt/IBM/tmp/install/fp9/was/WAS_V8.5.5.9_FOR_JSM_FOR_LINUX_ML.zip
    user: nms_exede_ci-cd
    password: AKCp2UNConPgDX6sZnkAoRQ1N8Qevm71RrHsTg86kEuC2BaYyeZfrhuRJX6StuSjUgaPNk5Hf
    force_basic_auth: yes
    status_code: 200,304
    creates: /opt/IBM/tmp/install/fp9/was/WAS_V8.5.5.9_FOR_JSM_FOR_LINUX_ML.zip
    timeout: 300

- unarchive:
    src: /opt/IBM/tmp/install/fp9/was/WAS_V8.5.5.9_FOR_JSM_FOR_LINUX_ML.zip
    dest: /opt/IBM/tmp/install/fp9/was/WAS_V8.5.5.9_FOR_JSM_FOR_LINUX_ML.zip
    remote_src: True

- name: Delete the zip file
  shell: "rm -f /opt/IBM/tmp/install/fp9/was/WAS_V8.5.5.9_FOR_JSM_FOR_LINUX_ML.zip" 
  become: true

- stat: path=/root/IBM/InstallationManager/eclipse/tools/imcl
  register: install_manager_path

- debug: msg="The install manager is not installed so it will be installed now."
  when: install_manager_path.stat.exists != True
- debug: msg="The install manager is installed so this step will be skipped."
  when: install_manager_path.stat.exists == True

- name: Install IBM Install Manager
  shell: "mydate=`date \"+%m-%d-%Y_%H:%M\"`; touch /root/install_mgr_install.log; cd /opt/IBM/tmp/install && /opt/IBM/tmp/install/im/userinstc --launcher.ini /opt/IBM/tmp/install/im/user-silent-install.ini -acceptLicense -ShowVerboseProgress -log /root/install_mgr_install.log; mv /root/install_mgr_install.log /root/install_mgr_install_${mydate}.log"
  become: true
  when: install_manager_path.stat.exists != True

- name: Install IBM Omnibus WebGUI Fixpack 9 
  shell: "mydate=`date \"+%m-%d-%Y_%H:%M\"`; touch /root/fixpack9_install.log; /root/IBM/InstallationManager/eclipse/tools/imcl -input /opt/viasat/omnibus/configs/webgui/fixpack-response.xml -silent -nosplash -acceptlicense -ShowVerboseProgress -log /root/fixpack9_install.log; mv /root/fixpack9_install.log /root/fixpack9_install_${mydate}.log"
  become: true
  when: webgui_version.stdout != "8.1.0.9"
  #when: install_manager_path.stat.exists != True

- name: Start the WebGUI server 
  shell: "/opt/IBM/JazzSM/profile/bin/startServer.sh server1 -script /opt/IBM/JazzSM/profile/bin/startJazz.sh"
  become: true
